#!/usr/bin/env python3
"""Emit staged db-sync SQL for scalable genesis UTxO tracing.

Unlike the bounded recursive proof query, this builds deduped server-side
stage tables one depth at a time.  It is intended for depth-10+ extraction and
cross-entity merge reconstruction without asking Postgres to hold the whole
recursive frontier in one planner-hostile CTE.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'lib'))

from chain_toolkit.anchors import load_anchors


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def ident(value: str) -> str:
    if not value.replace('_', '').isalnum() or value[0].isdigit():
        raise SystemExit(f'unsafe SQL identifier: {value!r}')
    return '"' + value.replace('"', '""') + '"'


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--schema', default='abcde_forensics_stage')
    ap.add_argument('--max-depth', type=int, default=10)
    ap.add_argument('--founders-only', action='store_true', help='stage only named founder roots (iog/emurgo/cf)')
    args = ap.parse_args()
    if args.max_depth < 0 or args.max_depth > 30:
        raise SystemExit('--max-depth must be between 0 and 30')

    anchors = load_anchors(ROOT / 'anchors.yaml')
    if args.founders_only:
        anchors = [a for a in anchors if a.seed_id in {'iog', 'emurgo', 'cf'}]
    if not anchors:
        raise SystemExit('no anchors selected')

    schema = ident(args.schema)
    values = ',\n'.join(
        f"  ({quote(a.seed_id)}, {quote(a.label)}, decode({quote(a.tx_hash)}, 'hex'), {a.amount_ada * 1_000_000})"
        for a in anchors
    )

    print(f"""-- Generated by scripts/build_staged_trace_sql.py. Read/write scope is limited to schema {args.schema}.
\\set ON_ERROR_STOP on
CREATE SCHEMA IF NOT EXISTS {schema};

DROP VIEW IF EXISTS {schema}.cross_entity_merges;
DROP VIEW IF EXISTS {schema}.cross_entity_merge_inputs;
DROP TABLE IF EXISTS {schema}.trace_frontier;
DROP TABLE IF EXISTS {schema}.trace_utxos;
DROP TABLE IF EXISTS {schema}.trace_spends;
DROP TABLE IF EXISTS {schema}.trace_roots;

CREATE UNLOGGED TABLE {schema}.trace_roots (
  root_seed_id text PRIMARY KEY,
  label text NOT NULL,
  seed_tx_hash bytea NOT NULL,
  amount_lovelace bigint NOT NULL
);

INSERT INTO {schema}.trace_roots(root_seed_id, label, seed_tx_hash, amount_lovelace)
VALUES
{values};

CREATE UNLOGGED TABLE {schema}.trace_utxos (
  root_seed_id text NOT NULL REFERENCES {schema}.trace_roots(root_seed_id),
  min_depth integer NOT NULL,
  tx_id bigint NOT NULL,
  tx_hash text NOT NULL,
  tx_out_index integer NOT NULL,
  value_lovelace numeric NOT NULL,
  address text,
  stake_address_id bigint,
  stake_address text,
  epoch_no integer,
  block_no integer,
  block_time_utc timestamp without time zone,
  first_seen_at timestamp without time zone DEFAULT now(),
  PRIMARY KEY(root_seed_id, tx_id, tx_out_index)
);

CREATE INDEX trace_utxos_utxo_idx ON {schema}.trace_utxos(tx_id, tx_out_index);
CREATE INDEX trace_utxos_depth_idx ON {schema}.trace_utxos(root_seed_id, min_depth);

CREATE UNLOGGED TABLE {schema}.trace_frontier (
  root_seed_id text NOT NULL,
  depth integer NOT NULL,
  tx_id bigint NOT NULL,
  tx_out_index integer NOT NULL,
  PRIMARY KEY(root_seed_id, tx_id, tx_out_index)
);

CREATE UNLOGGED TABLE {schema}.trace_spends (
  root_seed_id text NOT NULL,
  parent_tx_id bigint NOT NULL,
  parent_tx_out_index integer NOT NULL,
  spending_tx_id bigint NOT NULL,
  spending_tx_hash text NOT NULL,
  spending_epoch_no integer,
  spending_block_no integer,
  spending_block_time_utc timestamp without time zone,
  first_observed_depth integer NOT NULL,
  PRIMARY KEY(root_seed_id, parent_tx_id, parent_tx_out_index, spending_tx_id)
);

INSERT INTO {schema}.trace_utxos(
  root_seed_id, min_depth, tx_id, tx_hash, tx_out_index, value_lovelace,
  address, stake_address_id, stake_address, epoch_no, block_no, block_time_utc
)
SELECT
  r.root_seed_id,
  0 AS min_depth,
  tx.id AS tx_id,
  encode(tx.hash, 'hex') AS tx_hash,
  txo.index AS tx_out_index,
  txo.value AS value_lovelace,
  txo.address,
  txo.stake_address_id,
  sa.view AS stake_address,
  b.epoch_no,
  b.block_no,
  b.time AS block_time_utc
FROM {schema}.trace_roots r
JOIN public.tx tx ON tx.hash = r.seed_tx_hash
JOIN public.tx_out txo ON txo.tx_id = tx.id
LEFT JOIN public.stake_address sa ON sa.id = txo.stake_address_id
JOIN public.block b ON b.id = tx.block_id;

INSERT INTO {schema}.trace_frontier(root_seed_id, depth, tx_id, tx_out_index)
SELECT root_seed_id, min_depth, tx_id, tx_out_index
FROM {schema}.trace_utxos
WHERE min_depth = 0;

DO $$
DECLARE
  d integer;
  inserted_count integer;
BEGIN
  FOR d IN 1..{args.max_depth} LOOP
    INSERT INTO {schema}.trace_spends(
      root_seed_id, parent_tx_id, parent_tx_out_index, spending_tx_id,
      spending_tx_hash, spending_epoch_no, spending_block_no,
      spending_block_time_utc, first_observed_depth
    )
    SELECT DISTINCT
      f.root_seed_id,
      f.tx_id AS parent_tx_id,
      f.tx_out_index AS parent_tx_out_index,
      child_tx.id AS spending_tx_id,
      encode(child_tx.hash, 'hex') AS spending_tx_hash,
      child_block.epoch_no,
      child_block.block_no,
      child_block.time AS spending_block_time_utc,
      d AS first_observed_depth
    FROM {schema}.trace_frontier f
    JOIN public.tx_in spend
      ON spend.tx_out_id = f.tx_id
     AND spend.tx_out_index = f.tx_out_index
    JOIN public.tx child_tx ON child_tx.id = spend.tx_in_id
    JOIN public.block child_block ON child_block.id = child_tx.block_id
    WHERE f.depth = d - 1
    ON CONFLICT DO NOTHING;

    INSERT INTO {schema}.trace_utxos(
      root_seed_id, min_depth, tx_id, tx_hash, tx_out_index, value_lovelace,
      address, stake_address_id, stake_address, epoch_no, block_no, block_time_utc
    )
    SELECT DISTINCT
      f.root_seed_id,
      d AS min_depth,
      child_tx.id AS tx_id,
      encode(child_tx.hash, 'hex') AS tx_hash,
      child_out.index AS tx_out_index,
      child_out.value AS value_lovelace,
      child_out.address,
      child_out.stake_address_id,
      child_sa.view AS stake_address,
      child_block.epoch_no,
      child_block.block_no,
      child_block.time AS block_time_utc
    FROM {schema}.trace_frontier f
    JOIN public.tx_in spend
      ON spend.tx_out_id = f.tx_id
     AND spend.tx_out_index = f.tx_out_index
    JOIN public.tx child_tx ON child_tx.id = spend.tx_in_id
    JOIN public.tx_out child_out ON child_out.tx_id = child_tx.id
    LEFT JOIN public.stake_address child_sa ON child_sa.id = child_out.stake_address_id
    JOIN public.block child_block ON child_block.id = child_tx.block_id
    WHERE f.depth = d - 1
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;

    INSERT INTO {schema}.trace_frontier(root_seed_id, depth, tx_id, tx_out_index)
    SELECT root_seed_id, min_depth, tx_id, tx_out_index
    FROM {schema}.trace_utxos
    WHERE min_depth = d
    ON CONFLICT DO NOTHING;

    RAISE NOTICE 'depth %, new trace_utxos %', d, inserted_count;
    IF inserted_count = 0 THEN
      EXIT;
    END IF;
  END LOOP;
END $$;

DROP VIEW IF EXISTS {schema}.cross_entity_merge_inputs;
CREATE VIEW {schema}.cross_entity_merge_inputs AS
SELECT
  s.spending_tx_hash AS merge_tx_hash,
  s.spending_tx_id AS merge_tx_id,
  s.spending_epoch_no AS epoch_no,
  s.spending_block_no AS block_no,
  s.spending_block_time_utc AS block_time_utc,
  u.root_seed_id,
  u.min_depth AS input_min_depth,
  u.tx_hash AS input_tx_hash,
  u.tx_out_index AS input_tx_out_index,
  u.value_lovelace AS input_value_lovelace,
  u.address AS input_address,
  u.stake_address AS input_stake_address
FROM {schema}.trace_spends s
JOIN {schema}.trace_utxos u
  ON u.root_seed_id = s.root_seed_id
 AND u.tx_id = s.parent_tx_id
 AND u.tx_out_index = s.parent_tx_out_index;

DROP VIEW IF EXISTS {schema}.cross_entity_merges;
CREATE VIEW {schema}.cross_entity_merges AS
WITH per_tx AS (
  SELECT
    merge_tx_hash,
    merge_tx_id,
    min(epoch_no) AS epoch_no,
    min(block_no) AS block_no,
    min(block_time_utc) AS block_time_utc,
    array_agg(DISTINCT root_seed_id ORDER BY root_seed_id) AS roots,
    count(DISTINCT root_seed_id) AS root_count,
    count(*) AS traced_input_rows,
    sum(input_value_lovelace) AS traced_input_lovelace,
    min(input_min_depth) AS min_input_depth,
    max(input_min_depth) AS max_input_depth
  FROM {schema}.cross_entity_merge_inputs
  GROUP BY merge_tx_hash, merge_tx_id
)
SELECT
  merge_tx_hash,
  merge_tx_id,
  epoch_no,
  block_no,
  block_time_utc,
  array_to_string(roots, '+') AS root_combo,
  root_count,
  traced_input_rows,
  traced_input_lovelace,
  min_input_depth,
  max_input_depth
FROM per_tx
WHERE root_count >= 2;

-- machine-readable summaries for --csv callers
SELECT artifact, bucket, rows
FROM (
  SELECT 'trace_utxos' AS artifact, min_depth::text AS bucket, count(*) AS rows
  FROM {schema}.trace_utxos
  GROUP BY min_depth
  UNION ALL
  SELECT 'cross_entity_merges' AS artifact, root_combo AS bucket, count(*) AS rows
  FROM {schema}.cross_entity_merges
  GROUP BY root_combo
) summary
ORDER BY artifact, CASE WHEN bucket ~ '^[0-9]+$' THEN bucket::integer END NULLS LAST, bucket;
""")


if __name__ == '__main__':
    main()
